/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author AMD
 */
public class Inicio_GUI extends javax.swing.JFrame {

    /**
     * Creates new form Inicio_GUI
     */
    public Inicio_GUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        rec_BTN = new javax.swing.JButton();
        ates_BTN = new javax.swing.JButton();
        comp_BTN = new javax.swing.JButton();
        sair_BTN = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        rec_BTN.setText("Receituario");
        rec_BTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rec_BTNActionPerformed(evt);
            }
        });
        jPanel1.add(rec_BTN);
        rec_BTN.setBounds(60, 400, 700, 100);

        ates_BTN.setText("Atestado");
        ates_BTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ates_BTNActionPerformed(evt);
            }
        });
        jPanel1.add(ates_BTN);
        ates_BTN.setBounds(60, 100, 700, 100);

        comp_BTN.setText("Comparecimento");
        comp_BTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comp_BTNActionPerformed(evt);
            }
        });
        jPanel1.add(comp_BTN);
        comp_BTN.setBounds(60, 250, 700, 100);

        sair_BTN.setBackground(new java.awt.Color(255, 255, 255));
        sair_BTN.setForeground(new java.awt.Color(153, 0, 0));
        sair_BTN.setText("X");
        sair_BTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sair_BTNActionPerformed(evt);
            }
        });
        jPanel1.add(sair_BTN);
        sair_BTN.setBounds(683, 0, 110, 23);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 800, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(800, 600));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void comp_BTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comp_BTNActionPerformed
        try {
            Controller.Declaraçao_DAO.Impressão3();
        } catch (Exception ex) {
            Logger.getLogger(Inicio_GUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_comp_BTNActionPerformed

    private void sair_BTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sair_BTNActionPerformed
    System.exit(0);
    }//GEN-LAST:event_sair_BTNActionPerformed

    private void ates_BTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ates_BTNActionPerformed
        try {
            Controller.Atestado_DAO.Impressão();
        } catch (Exception ex) {
            Logger.getLogger(Inicio_GUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_ates_BTNActionPerformed

    private void rec_BTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rec_BTNActionPerformed
        try {
            Controller.Receituario_DAO.Impressão2();
        } catch (Exception ex) {
            Logger.getLogger(Inicio_GUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_rec_BTNActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inicio_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inicio_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inicio_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inicio_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Inicio_GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ates_BTN;
    private javax.swing.JButton comp_BTN;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton rec_BTN;
    private javax.swing.JButton sair_BTN;
    // End of variables declaration//GEN-END:variables
}
